### ISSUE TITLE
42.3 fails on stage 2

### ISSUE THREAD

**Issue by denisok** [openSUSE/vagrant-ceph#6]
> Ended stage: ceph.stage.2 succeeded=11/14 failed=3/14 time=27.6s                                           
>                                                                                                            
> Failures summary:                                                                                         S
>                                                                                                            
> validate.discovery (/srv/modules/runners/validate.py):                                                     
>   Exception occurred in runner validate.discovery: Traceback (most recent call last):                      
>     File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low                       
>       data['return'] = self.functions[fun](*args, **kwargs)                                                
>     File "/srv/modules/runners/validate.py", line 972, in discovery                                        
>       valid.lint_yaml_files()                                                                              
>     File "/srv/modules/runners/validate.py", line 829, in lint_yaml_files                                  
>       accum_files = self._accumulate_files_from(policy_file)                                               
>     File "/srv/modules/runners/validate.py", line 784, in _accumulate_files_from                           
>       files = self._parse(proposals_dir + "/" + line)                                                      
>     File "/srv/modules/runners/validate.py", line 856, in _parse                                           
>       key, value = keyvalue.split('=')                                                                     
>   ValueError: need more than 1 value to unpack                                                             
>                                                                                                            
> push.proposal (/srv/modules/runners/push.py):                                                              
>   Exception occurred in runner push.proposal: Traceback (most recent call last):                           
>     File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low                       
>       data['return'] = self.functions[fun](*args, **kwargs)                                                
>     File "/srv/modules/runners/push.py", line 87, in proposal                                              
>       common = pillar_data.organize(filename)                                                              
>     File "/srv/modules/runners/push.py", line 253, in organize                                             
>       files = _parse(self.proposals_dir + "/" + line)                                                      
>     File "/srv/modules/runners/push.py", line 368, in _parse                                               
>       filter_type, value = optional.split('=')                                                             
>   ValueError: need more than 1 value to unpack                                                             
>                                                                                                            
> ceph.monitoring (/srv/salt/ceph/monitoring):                                                               
>   admin.ceph:                                                                                              
>     The require statement in state '/etc/prometheus/ses_nodes' in SLS 'ceph.monitoring.prometheus.update_  
> service_discovery' needs to be formed as a list

**Comment by denisok** [comment]
>  [13/14]   ceph.monitoring on                                                  
>             |_ select.minions(cluster=ceph, host=False).............. ✓ (0.1s)
>             |_ select.minions(cluster=ceph, host=False).............. ✓ (0.0s)
>             |_ select.minions(cluster=ceph, roles=rgw)............... ✓ (0.1s)
>           admin.ceph................................................. ❌ (3s) 
>             |_ pkg.installed(golang-github-prometheus-prometheus).... ⏳      
>             |_ file.managed(/etc/prometheus/prometheus.yml).......... ⏳      
>             |_ pkg.installed(golang-github-prometheus-alertmanager).. ⏳      
>             |_ pkg.installed(grafana)................................ ⏳      

Ii is reproducible with files. If I say to not copy it and create they manually, this doesn't appear.

**Comment by denisok** [comment]
salt-run state.orch ceph.stage.0

>[ERROR   ] Run failed on minions: admin.ceph
> Failures:
>     admin.ceph:
>         Data failed to compile:
>     ----------
>         Rendering SLS 'base:ceph.salt-api.configure' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'deepsea.user'

but it proceeds, update kernel and restarts

salt-run state.orch ceph.stage.0 second time runs OK.

salt-run state.orch ceph.stage.1 runs OK.

salt-run state.orch ceph.stage.2 fails:

> [ERROR   ] Run failed on minions: admin.ceph
> Failures:
>     admin.ceph:
>         Data failed to compile:
>     ----------
>         The require statement in state '/etc/prometheus/ses_nodes' in SLS 'ceph.monitoring.prometheus.
> update_service_discovery' needs to be formed as a list
> 
> admin.ceph_master:
> ----------
>           ID: push proposals
>     Function: salt.runner
>         Name: push.proposal
>       Result: False
>      Comment: Exception occurred in runner push.proposal: Traceback (most recent call last):
>                 File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 395, in _low
>                   data['return'] = self.functions[fun](*args, **kwargs)
>                 File "/srv/modules/runners/push.py", line 87, in proposal
>                   common = pillar_data.organize(filename)
>                 File "/srv/modules/runners/push.py", line 253, in organize
>                   files = _parse(self.proposals_dir + "/" + line)
>                 File "/srv/modules/runners/push.py", line 368, in _parse
>                   filter_type, value = optional.split('=')
>               ValueError: need more than 1 value to unpack
>      Started: 11:21:42.891639
>     Duration: 1333.554 ms
>

**Comment by denisok** [comment]
It is an typo in the proposals/policy.cfg

https://github.com/openSUSE/vagrant-ceph/blob/master/files/salt/openSUSE-42.3-x86_64_tiny/srv/pillar/ceph/proposals/policy.cfg#L1

will fix it
